# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from relative_angle_nb/Apl.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Apl(genpy.Message):
  _md5sum = "9809d650616fd3c284b0b4b27cd2e9fe"
  _type = "relative_angle_nb/Apl"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint16 obs_dist
float32 obs_direct
float32 goal_x
float32 goal_y
int32 obs_latelitude"""
  __slots__ = ['obs_dist','obs_direct','goal_x','goal_y','obs_latelitude']
  _slot_types = ['uint16','float32','float32','float32','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       obs_dist,obs_direct,goal_x,goal_y,obs_latelitude

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Apl, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.obs_dist is None:
        self.obs_dist = 0
      if self.obs_direct is None:
        self.obs_direct = 0.
      if self.goal_x is None:
        self.goal_x = 0.
      if self.goal_y is None:
        self.goal_y = 0.
      if self.obs_latelitude is None:
        self.obs_latelitude = 0
    else:
      self.obs_dist = 0
      self.obs_direct = 0.
      self.goal_x = 0.
      self.goal_y = 0.
      self.obs_latelitude = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_H3fi().pack(_x.obs_dist, _x.obs_direct, _x.goal_x, _x.goal_y, _x.obs_latelitude))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 18
      (_x.obs_dist, _x.obs_direct, _x.goal_x, _x.goal_y, _x.obs_latelitude,) = _get_struct_H3fi().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_H3fi().pack(_x.obs_dist, _x.obs_direct, _x.goal_x, _x.goal_y, _x.obs_latelitude))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 18
      (_x.obs_dist, _x.obs_direct, _x.goal_x, _x.goal_y, _x.obs_latelitude,) = _get_struct_H3fi().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_H3fi = None
def _get_struct_H3fi():
    global _struct_H3fi
    if _struct_H3fi is None:
        _struct_H3fi = struct.Struct("<H3fi")
    return _struct_H3fi
